### ISSUE TITLE
N shows as ん in on’yomi readings

### ISSUE THREAD

**Issue by andresovela** [davidsansome/tsurukame#188] opened 2019-11-01 19:47 UTC
See screenshot. (I know the reading is not correct)
![73437A1A-23DC-460B-99D3-261A84200E12](https://user-images.githubusercontent.com/8990961/68051889-c63cdb00-fce8-11e9-84e7-375bcaeed921.png)

**Comment by davidsansome** [comment] 2019-11-05 03:08
I think this is a duplicate of #161 which will be fixed in the next release

**Closed by davidsansome** 2019-11-05 03:08 UTC
