### ISSUE TITLE
Feature request: improve the user note feature

### ISSUE THREAD

**Issue by ater1267** [davidsansome/tsurukame#361] opened 2020-06-11 11:25 UTC
First of all, I'd like to say that I like the Tsurukame app very much, I use it all the time.

Recently, Tsurukame started to show the user note field in the kanji/vocabulary information screen.  I must say, it was a life saver for me.  I use user notes very heavily, and before that I had to switch to the WaniKani app in the mobile Chrome constantly, which was very time consuming.  So thank you for introducing this feature!

I'd like to request a couple improvements:

1. There are two different note fields in WaniKani, the "Meaning Note" field and the "Reading Note" field.  However, Tsurukame only shows one field instead of two.  What would happen if both these fields are non-empty in WaniKani? 

In any case, please **show these two note fields separately** in Tsurukame as well.  I'd say show them below the corresponding "Meaning Mnemonic" and "Reading Mnemonic" fields, just like they are shown in WaniKani.

2. Please enable **adding and editing** the "Meaning Note" and "Reading Note" fields via the Tsurukame app interface.  This way, this feature will be complete.

Thank you.

**Comment by turtlemaster19** [comment] 2020-06-12 13:19
@ater1267 I agree about this. However, this is actually a duplicate of a much older issue that's still open, namely #27.

**Closed** 2021-07-12 22:18 UTC
