### ISSUE TITLE
iOS 13 Dark Mode

### ISSUE THREAD

**Issue by turtlemaster19** [davidsansome/tsurukame#142] opened 2019-07-16 13:00 UTC
This is a reminder to make sure this app works properly with Dark Mode. Thank you!

**Comment by turtlemaster19** [comment] 2019-10-07 12:42
I think that on reading - the system keyboard should be dark instead of light, to help make it more obvious which one it wants. Just a suggestion after looking at the app in iOS 13.

**Comment by davidsansome** [comment] 2019-10-29 00:59
Yep I'd definitely like to support this.
Duplicate of #97 though.

**Closed by davidsansome** 2019-10-29 00:59 UTC
