### ISSUE TITLE
iOS 13 Dark Mode Not Working 

### ISSUE THREAD

**Issue by Kosezu** [davidsansome/tsurukame#203] opened 2019-11-13 09:08 UTC
Most recent app version 1.14 references iOS 13 Dark Mode issue fixed, but there is no dark mode function on the app. 

Is there in fact a dark mode?

**Comment by davidsansome** [comment] 2019-11-13 13:28
Duplicate of #198

**Closed by davidsansome** 2019-11-13 13:28 UTC

**Comment by turtlemaster19** [comment] 2019-11-14 14:17
@Kosezu No, not yet, it wasn't supposed to be added. That's why #97 is still open

**Comment by Kosezu** [comment] 2019-11-15 02:53
@turtlemaster19 could you please add a dark mode to the app??

I spend a decent amount of time studying at night and it would be a very great help!

**Comment by turtlemaster19** [comment] 2019-11-15 13:21
I agree, that's why the other issue is still open. It's not exactly easy to add new features, though.
