### ISSUE TITLE
App crashes at level 5, vocab word “これ“

### ISSUE THREAD

**Issue by serenityengineer** [davidsansome/tsurukame#638] opened 2023-05-25 21:51 UTC
When I click lessons, これ is displayed along with its information but the app freezes at that point. I have tried refreshing the app and my phone but it’s still doing this.

**Comment by fstraetz** [comment] 2023-05-25 22:06
Came here to report this exact issue. And I'm pretty sure the same thing happened to my girlfriend, though I'm not sure whether the problem was with これ in her case (i. e. this problem might occur for other non-kanji vocab).

A simple workaround is to do the lessons using the WaniKani website. After a refresh of the Tsurukame data (swipe down) the erroneous lesson is "gone" and everything works again. 

Time will tell how this vocab / these vocabs will behave during reviews.

**Comment by carloscheddar** [comment] 2023-05-25 22:18
Having the same issue at  level 12, clicking "Lessons" will crash the app. It was working yesterday so it could either be the latest update or there's something wrong with the lessons that I have up next.

**Comment by davidsansome** [comment] 2023-05-25 22:37
Duplicate of #636

**Closed by davidsansome** 2023-05-25 22:37 UTC
