### ISSUE TITLE
Text is not readable in dark mode

### ISSUE THREAD

**Issue by garrettcampagna** [davidsansome/tsurukame#204] opened 2019-11-13 13:03 UTC
Many of the backgrounds in the app are now adjusting based on the user's dark mode setting but the text is not changing so it's unreadable. 
Until this is resolved, please allow the user to toggle dark mode within the app, separately from the iOS-wide dark mode setting.

**Comment by davidsansome** [comment] 2019-11-13 13:28
Duplicate of #198

**Closed by davidsansome** 2019-11-13 13:28 UTC

**Comment by garrettcampagna** [comment] 2019-11-13 17:34
I apologize. I didn’t see that issue and didn’t have the update available yet. I see it’s fixed now and appreciate it!
