### ISSUE TITLE
Combine Tool Not Working (missing subject 4169)

### ISSUE THREAD

**Issue by jeff-bacon** [davidsansome/tsurukame#247] opened 2019-12-25 22:24 UTC
Running the scrapper finishes without error but only takes 4 minutes while the documentation says that it should take roughly an hour.  Afterwards I try to combine the contents of the data folder into the data.bin file with the command listed in the docs.  I get an error stating that the subject 4169 is missing.  I've verified that the file is indeed missing from the data folder.

Is this a problem with the scrapper not downloading all the necessary files or a problem with the combine tool looking for files it shouldn't be looking for?

**Comment by turtlemaster19** [comment] 2019-12-25 22:32
Dupe of #233.
Merry Christmas and Happy Holidays!

**Comment by jeff-bacon** [comment] 2019-12-25 22:37
Merry Christmas!

I've looked through #233 and I'm not getting timeout errors when running the scrapper.  Is there a way to get a prebuilt data.bin file or am I out of luck until this bug gets fixed?

**Comment by turtlemaster19** [comment] 2019-12-25 22:39
Timeout errors won't stop it. If you try to download again, will it show an error for whichever item is missing?

P.S. You could get a prebuilt data.bin, but I would need to build it before I could send it to you.

**Comment by jeff-bacon** [comment] 2019-12-25 22:44
I'm not in a huge hurry to poke around with tsurukame, I just wanted something to do over the holiday!  So please don't go out of your way to provide the data.bin.  Was going to see if I could get it compiled and running on MacOS.

Running the scrapper a second time gives me the following output:

<img width="566" alt="Screen Shot 2019-12-25 at 2 41 58 PM" src="https://user-images.githubusercontent.com/17691864/71451143-beb41400-2724-11ea-9664-4c478d572eb6.png">

**Comment by turtlemaster19** [comment] 2019-12-26 00:00
Subject ID 4169 is https://www.wanikani.com/vocabulary/%E4%B9%B1%E4%BA%A4-4169 (orgy; level 19). Are you able to visit the site? I can't.

**Comment by jeff-bacon** [comment] 2019-12-26 00:04
I'm not able to reach ID 4169 on wanikani.  That may explain why it's not being downloaded.  I'm not seeing an entry for "orgy" on the level 19 page either.

**Comment by turtlemaster19** [comment] 2019-12-26 00:05
Here's the data entry if that helps.
`{"id":4169,"object":"vocabulary","url":"https://api.wanikani.com/v2/subjects/4169","data_updated_at":"2019-12-24T23:41:12.841269Z","data":{"created_at":"2012-11-01T03:38:26.911683Z","level":19,"slug":"乱交-4169","hidden_at":"2019-12-24T23:41:08.515772Z","document_url":"https://www.wanikani.com/vocabulary/%E4%B9%B1%E4%BA%A4-4169","characters":"乱交","meanings":[{"meaning":"Orgy","primary":true,"accepted_answer":true},{"meaning":"Promiscuity","primary":false,"accepted_answer":true}],"auxiliary_meanings":[],"readings":[{"primary":true,"reading":"らんこう","accepted_answer":true}],"parts_of_speech":["noun","する verb","の adjective"],"component_subject_ids":[1079,565],"meaning_mnemonic":"A big \u003ckanji\u003emix\u003c/kanji\u003e of folks forming a kind of \u003ckanji\u003eriot\u003c/kanji\u003e. You'd think this would be something more violent, but it's really just an \u003cvocabulary\u003eorgy\u003c/vocabulary\u003e. Lots of mixing, I guess, and not very much organization on the orgy-organizer's part, at least according to this kanji sequence.","reading_mnemonic":"This is a jukugo word, which usually means on'yomi readings from the kanji. If you know the readings of your kanji you'll know how to read this as well.","context_sentences":[{"en":"Her tongue lolled out and she passed out during the orgy.","ja":"かの女は、乱交のと中で、舌をだらりと出して気ぜつしてしまったんです。"},{"en":"Hey, it's about time you quit it with the promiscuity, you've been putting everybody off.","ja":"いい加減、乱交するのは止めなよ。みんなドン引きだよ。"},{"en":"\"I look so good today, I may be asked to join an orgy.\" \"Haha. You wish!\"","ja":"「何か今日の俺、マジでイケてる。ひょっとしたらアイツらの乱交パーティにも誘われちゃうかも。」「ははは〜。そうだといいね。」"}],"pronunciation_audios":[{"url":"https://cdn.wanikani.com/audios/30254-subject-4169.ogg?1553789087","metadata":{"gender":"female","source_id":22779,"pronunciation":"らんこう","voice_actor_id":1,"voice_actor_name":"Kyoko","voice_description":"Tokyo accent"},"content_type":"audio/ogg"},{"url":"https://cdn.wanikani.com/audios/30245-subject-4169.mp3?1553789086","metadata":{"gender":"female","source_id":22779,"pronunciation":"らんこう","voice_actor_id":1,"voice_actor_name":"Kyoko","voice_description":"Tokyo accent"},"content_type":"audio/mpeg"},{"url":"https://cdn.wanikani.com/audios/20980-subject-4169.ogg?1547884138","metadata":{"gender":"male","source_id":4517,"pronunciation":"らんこう","voice_actor_id":2,"voice_actor_name":"Kenichi","voice_description":"Tokyo accent"},"content_type":"audio/ogg"},{"url":"https://cdn.wanikani.com/audios/20977-subject-4169.mp3?1547884137","metadata":{"gender":"male","source_id":4517,"pronunciation":"らんこう","voice_actor_id":2,"voice_actor_name":"Kenichi","voice_description":"Tokyo accent"},"content_type":"audio/mpeg"}],"lesson_position":45}}`

**Comment by turtlemaster19** [comment] 2019-12-26 00:15
Here's a ZIP file containing the data.bin without item 4169, for now: [data.bin.zip](https://github.com/davidsansome/tsurukame/files/4000944/data.bin.zip)
I submitted a ticket with WK, but given that it's Christmas, it might be a while before it's fixed.

**Comment by jeff-bacon** [comment] 2019-12-26 00:19
Thanks a lot @turtlemaster19!

**Comment by vietqhoang** [comment] 2019-12-26 02:40
> Here's the data entry if that helps.
> `{"id":4169,"object":"vocabulary","url":"https://api.wanikani.com/v2/subjects/4169","data_updated_at":"2019-12-24T23:41:12.841269Z","data":{"created_at":"2012-11-01T03:38:26.911683Z","level":19,"slug":"乱交-4169","hidden_at":"2019-12-24T23:41:08.515772Z","document_url":"https://www.wanikani.com/vocabulary/%E4%B9%B1%E4%BA%A4-4169","characters":"乱交","meanings":[{"meaning":"Orgy","primary":true,"accepted_answer":true},{"meaning":"Promiscuity","primary":false,"accepted_answer":true}],"auxiliary_meanings":[],"readings":[{"primary":true,"reading":"らんこう","accepted_answer":true}],"parts_of_speech":["noun","する verb","の adjective"],"component_subject_ids":[1079,565],"meaning_mnemonic":"A big \u003ckanji\u003emix\u003c/kanji\u003e of folks forming a kind of \u003ckanji\u003eriot\u003c/kanji\u003e. You'd think this would be something more violent, but it's really just an \u003cvocabulary\u003eorgy\u003c/vocabulary\u003e. Lots of mixing, I guess, and not very much organization on the orgy-organizer's part, at least according to this kanji sequence.","reading_mnemonic":"This is a jukugo word, which usually means on'yomi readings from the kanji. If you know the readings of your kanji you'll know how to read this as well.","context_sentences":[{"en":"Her tongue lolled out and she passed out during the orgy.","ja":"かの女は、乱交のと中で、舌をだらりと出して気ぜつしてしまったんです。"},{"en":"Hey, it's about time you quit it with the promiscuity, you've been putting everybody off.","ja":"いい加減、乱交するのは止めなよ。みんなドン引きだよ。"},{"en":"\"I look so good today, I may be asked to join an orgy.\" \"Haha. You wish!\"","ja":"「何か今日の俺、マジでイケてる。ひょっとしたらアイツらの乱交パーティにも誘われちゃうかも。」「ははは〜。そうだといいね。」"}],"pronunciation_audios":[{"url":"https://cdn.wanikani.com/audios/30254-subject-4169.ogg?1553789087","metadata":{"gender":"female","source_id":22779,"pronunciation":"らんこう","voice_actor_id":1,"voice_actor_name":"Kyoko","voice_description":"Tokyo accent"},"content_type":"audio/ogg"},{"url":"https://cdn.wanikani.com/audios/30245-subject-4169.mp3?1553789086","metadata":{"gender":"female","source_id":22779,"pronunciation":"らんこう","voice_actor_id":1,"voice_actor_name":"Kyoko","voice_description":"Tokyo accent"},"content_type":"audio/mpeg"},{"url":"https://cdn.wanikani.com/audios/20980-subject-4169.ogg?1547884138","metadata":{"gender":"male","source_id":4517,"pronunciation":"らんこう","voice_actor_id":2,"voice_actor_name":"Kenichi","voice_description":"Tokyo accent"},"content_type":"audio/ogg"},{"url":"https://cdn.wanikani.com/audios/20977-subject-4169.mp3?1547884137","metadata":{"gender":"male","source_id":4517,"pronunciation":"らんこう","voice_actor_id":2,"voice_actor_name":"Kenichi","voice_description":"Tokyo accent"},"content_type":"audio/mpeg"}],"lesson_position":45}}`

If you look at this payload you’ll see the field `hidden_at` is timestamped. This means the subject has been removed from the WK public view. In other words it is no longer being displayed and not reviewable.

You can read up on the field via our documentation:

https://docs.api.wanikani.com/20170710/#subjects

**Comment by vietqhoang** [comment] 2019-12-26 02:45
> Here's a ZIP file containing the data.bin without item 4169, for now: [data.bin.zip](https://github.com/davidsansome/tsurukame/files/4000944/data.bin.zip)
> I submitted a ticket with WK, but given that it's Christmas, it might be a while before it's fixed.

I believe there is a reason why there isn’t a hosted compiled bin on the project. Please reconsider sharing this.

**Comment by davidsansome** [comment] 2019-12-26 02:50
I've removed the link to the data.bin - we're not allowed to host it because it contains content that is only accessible to WaniKani subscribers!

**Comment by jeff-bacon** [comment] 2019-12-26 02:52
> I believe there is a reason why there isn’t a hosted compiled bin on the project. Please reconsider sharing this.

@vietqhoang I understand why this isn't provided as part of tsurukame as the data comes from WaniKani which is a paid-for service.  @turtlemaster19 I believe I can get by with just the missing data since I've been able to get the rest by using my API key.

As for the bug with the combine tool, is it possible to have it only require entries where hidden_at is null?

**Comment by vietqhoang** [comment] 2019-12-26 02:58
> As for the bug with the combine tool, is it possible to have it only require entries where hidden_at is null?

Not sure how the tool is written. For the API we have a parameter available to return only subjects based on the hidden state.

See `hidden` under the [parameters section](https://docs.api.wanikani.com/20170710/#get-all-subjects) of the API documentation for the `/subjects` endpoint.

**Comment by jeff-bacon** [comment] 2019-12-26 03:01
> For the API we have a parameter available to return only subjects based on the hidden state.

Ah excellent, it's already built into the API.  This will make for a clean fix.  Thanks @vietqhoang.

**Comment by turtlemaster19** [comment] 2019-12-26 15:59
@vietqhoang Sorry about that. Please delete the link in your revision history, since it's still there. Thank you for reaching out about this!

The only reason I didn't try to share it some other way was [this post](https://community.wanikani.com/t/wanikani-items-now-public/37587)

**Comment by davidsansome** [comment] 2019-12-30 14:47
I think Tsurukame is already correctly ignoring hidden items.

The issue is that Orgy (4169) is still referenced in the amalgamation_subject_ids list for the 交 kanji (565).  Tsurukame is sanity checking it's got all the subjects it needs, and is failing because it's missing this one.

@vietqhoang would you be able to remove 4169 from the amalgamation_subject_ids list for 565?

**Comment by vietqhoang** [comment] 2019-12-30 14:49
Odd. It should ‘t be showing up. I’ll investigate and make the corrections by next business day. Will let you know when its done.

**Comment by vietqhoang** [comment] 2019-12-31 06:06
I was able to confirm the issue. I was also able to trace the problem with our end on why the hidden subject is showing up. I will have a pull request up to address this issue.

For the time being I went ahead and refreshed our API cache for all subjects. I can confirm for subject 565 it is no longer listing 4169 under `amalgamation_subject_ids`.

**Comment by davidsansome** [comment] 2019-12-31 06:24
That's awesome, thank you so much!

**Closed by davidsansome** 2019-12-31 06:24 UTC

**Comment by turtlemaster19** [comment] 2019-12-31 10:58
> Running the scrapper finishes without error but only takes 4 minutes while the documentation says that it should take roughly an hour.

@jeff-bacon, depends on your Internet connection. Glad it wasn’t just me though, and that the tool finally works correctly.

**Comment by turtlemaster19** [comment] 2020-01-13 01:10
@vietqhoang, you hid 今日は (item 7564) which is still showing up for subject 476 (日)

**Comment by vietqhoang** [comment] 2020-01-13 01:12
Yeah. Our content team hid it the other day. The code changes to address the cache refresh is still being reviewed. I’ll force refresh the cache manually. Will update when it happens.

**Comment by turtlemaster19** [comment] 2020-01-13 01:15
Okay. I'll start greeting people with 七千五百六十四 and figure that they'll understand. :wink:
Thank you for your effort, although I don't understand the purpose of hiding it, which was performed at `2020-01-10T23:45:48.511534Z`

**Comment by vietqhoang** [comment] 2020-01-13 01:19
I wouldn’t be the one to ask since I am not involved in content. Can’t give you an answer since I don’t know. Best way to get an answer is sending an email to hello@wanikani.com and someone from Content will be able to answer the question. Or a post on the boards.

**Comment by turtlemaster19** [comment] 2020-01-13 01:20
Thank you, and I'm sorry to bother you. I can tell that you're working hard with what you do have, and I appreciate your assistance.

**Comment by vietqhoang** [comment] 2020-01-13 01:25
No problem. The cache thing is the fault of my end. Sorry I couldn’t provide an answer to your other questions.

**Comment by turtlemaster19** [comment] 2020-01-13 01:30
@vietqhoang No, I completely understand. Just waiting to hear that the cache has been cleared.

**Comment by vietqhoang** [comment] 2020-01-13 01:31
Recalled the following content change log topic exists:

https://community.wanikani.com/t/wanikani-content-updates/33117/52

But the recently hidden subject in question is not listed. Inquiring about it with the content team now.

**Comment by vietqhoang** [comment] 2020-01-13 01:32
> @vietqhoang No, I completely understand. Just waiting to hear that the cache has been cleared.

It’ll be a couple hours. Unfortunately I don’t have access to my workstation at the moment. Will be one of the first things I’ll do. Sorry for the inconvenience.

**Comment by turtlemaster19** [comment] 2020-01-13 01:32
@vietqhoang Neither is the forbidden subject 4169 which was removed December 24, 2019 at 23:41:08.515772 UTC which caused this issue originally.

**Comment by turtlemaster19** [comment] 2020-01-13 01:34
@vietqhoang Thank you. I completely understand, especially since I have been the one waiting to be at the other computer to try to fix an issue just yesterday.

**Comment by vietqhoang** [comment] 2020-01-13 04:19
@turtlemaster19 I have refreshed the cache. It looks like the components have been updated as well. Can you confirm?

To follow-up on the question on why the subject was removed (for reference for those coming into this conversation):

https://community.wanikani.com/t/今日は-こんにちは-is-gone-from-level-3-vocab-no-one-cares/41335

Thanks for your patience and sorry about the inconvenience.

**Comment by turtlemaster19** [comment] 2020-01-13 13:57
@vietqhoang No, thank you! I hope your PR is merged and the force-refresh works now. Hopefully I won't have to mention you again!
