### ISSUE TITLE
Some text is clipped on iPhone

### ISSUE THREAD

**Issue by allanw** [davidsansome/tsurukame#718] opened 2024-06-06 01:53 UTC
In some example sentences, the text is truncated. Please see the last example sentence in the screenshot which ends with “the engine will”

![IMG_1775](https://github.com/davidsansome/tsurukame/assets/237499/19e6445a-fed6-4b06-b04e-67f2d835040b)

I’m using an iPhone 14 Pro Max with iOS 17.5.1

**Comment by davidsansome** [comment] 2024-06-06 01:58
I think this is a duplicate of #695

**Closed by davidsansome** 2024-06-06 01:58 UTC
