### ISSUE TITLE
End review session leads to a crash

### ISSUE THREAD

**Issue by Rion-Kaneshiro** [davidsansome/tsurukame#167] opened 2019-08-20 10:39 UTC
I don’t know if this is iOS 13 specific but on my iOS 13 device the app crashed every time „end review session“ is tapped.

In some way it actually does what it says, but could be more graceful ^^‘

**Comment by lyallcooper** [comment] 2019-08-20 21:03
Duplicate of #162?

**Comment by Rion-Kaneshiro** [comment] 2019-08-21 15:59
Yes, but it happens on the iPhone as well.
I‘ll comment that in #162

**Closed** 2019-10-07 07:46 UTC
