### ISSUE TITLE
App unexpectedly crashes

### ISSUE THREAD

**Issue by pfif** [davidsansome/tsurukame#660] opened 2023-09-14 23:34 UTC
Hi!

I love Tsurukame, I have been using it for years now. Thank you for all the work you put on it.

I am writing to report a bug. I unfortunately do not have much details - whenever I do reviews, at some point, the app simply crashes. I do not have any stacktrace to share.
It has been two days that this behavior has been happening.

How can I help you solve this issue?

Thank you for your time,
Pfif

**Comment by UInt2048** [comment] 2023-09-14 23:48
Duplicate of #658

**Comment by UInt2048** [comment] 2023-09-14 23:49
We’ve got it fixed; we’re just waiting for App Store approval

**Comment by pfif** [comment] 2023-09-15 02:54
Thanks

**Closed** 2023-09-15 14:27 UTC
