### ISSUE TITLE
Break line on reviews?

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#411] opened 2020-09-28 15:25 UTC
![image](https://user-images.githubusercontent.com/15106299/94452074-0c274b00-01a7-11eb-8252-a6fb0e92cfdc.jpeg)

I find that truncation is probably less than ideal for the case of this app. Any reason not to break onto two lines? If not i can submit a PR.

**Comment by UInt2048** [comment] 2020-09-29 11:07
@abdulajet Please do submit a PR. It's already a bug (this is a duplicate of #313)

**Comment by abdulajet** [comment] 2020-09-29 11:12
👍🏿

**Comment by UInt2048** [comment] 2020-10-01 11:05
@abdulajet If at all possible, can you close _this_ issue since we already have it on the issue tracker at #313?

**Closed** 2020-10-01 11:06 UTC
