### ISSUE TITLE
Feature request: include wanikani's  "Patterns of Use"

### ISSUE THREAD

**Issue by stoifgiear** [davidsansome/tsurukame#665] opened 2023-09-19 02:25 UTC
Hi! Love studying with tsurukame but often I resort to doing my lessons on my computer or on the website (when using my phone). In lessons Wanikani has "Patterns of Use" section right above the context sentences which I find super helpful. It would be great if these could be added to Tsurukame.

**Comment by UInt2048** [comment] 2023-09-19 10:56
Duplicate of #546

**Closed** 2023-09-30 00:39 UTC
