### ISSUE TITLE
New items don’t appear in Tsurukame

### ISSUE THREAD

**Issue by marifly** [davidsansome/tsurukame#359] opened 2020-05-24 12:15 UTC
On May 22 WaniKani added a vocab item.

_広がる_ - published new _vocabulary_ 

This appears in my reviews in WaniKani using a web browser but not in the app.

**Comment by turtlemaster19** [comment] 2020-05-25 00:46
@marifly Duplicate of #180

**Comment by smearedink** [comment] 2020-05-29 14:29
I came here due to this exact issue, so I’m glad to see it’s been brought up. I’ve done 100% of my WaniKani through Tsurukame so far (love it, thank you).

I just want to check—as long as this mismatch persists, if I just stay on top of that one vocab item through the web interface and do everything else through Tsurukame, there’s no issue once this vocab is properly picked up by Tsurukame?

**Comment by turtlemaster19** [comment] 2020-05-30 15:18
@smearedink WaniKani won't allow you to submit (nor give any reviews for) a moved item until you reach the level that it has been moved to.

**Comment by smearedink** [comment] 2020-05-30 18:02
I’m a bit confused - has 広がる been moved from a different level? I thought from the first post that it was newly added vocab. (The very similar 拡がる does appear in my still-to-come level 5 vocab in Tsurukame.)

**Comment by turtlemaster19** [comment] 2020-05-31 14:04
@smearedink Oops my bad, you're right.

**Comment by smearedink** [comment] 2020-05-31 14:10
Good to know, thank you!

**Comment by janthony01** [comment] 2020-07-01 15:01
Having the same issue — I’m level 60, so all of the new items should be available to me. They will only show up on the official WK interface. Even after learning them, they will not show up in reviews in Tsurukame.

**Comment by turtlemaster19** [comment] 2020-07-01 15:55
@janthony01 David Sansome is planning on updating Tsurukame to the latest data hopefully by the weekend. See the forum thread.

**Comment by andrew-katsewich** [comment] 2020-08-26 06:38
Actually still 1 (at least) missing, level 3, イギリス人.

**Comment by SpasiboKojima** [comment] 2020-08-26 06:39
Actually still 1 (at least) missing, level 3, イギリス人.

**Comment by UInt2048** [comment] 2020-08-26 12:00
@SpasiboKojima That was moved from level 17 afterward. This is a dupe of #180 - the only reason any of this is occurring is because we have a static database.

**Comment by davidsansome** [comment] 2021-03-19 09:56
This should be fixed in the next release - the static database is gone and we download updates from the WaniKani API at runtime.

**Closed by davidsansome** 2021-03-19 09:56 UTC
