### ISSUE TITLE
Next level-up review always displays “Now”

### ISSUE THREAD

**Issue by mircah** [davidsansome/tsurukame#473] opened 2021-06-28 16:13 UTC
Not a big deal, but the value of this field “next level-up review” never seems to change - always reads “now”.

**Comment by UInt2048** [comment] 2021-06-29 14:27
@mircah Cannot reproduce - shows as 5 days, 20 hours for me.

Do you happen to have any current-level kanji or radicals available for review?

**Comment by mircah** [comment] 2021-06-29 16:05
No lessons, no reviews. If I click on “show remaining” i can see that next reviews are in 3 hrs. 

Just reset my levels back to the beginning the other day, in case that’s a factor. 

Tamara

**Comment by UInt2048** [comment] 2021-06-30 14:28
Yes, that's likely the factor. In that case, it's the same problem as  #467.

Please close this issue if logging out and back in solves your problem.

**Closed** 2021-06-30 19:57 UTC
