### ISSUE TITLE
Level change messes up reviews

### ISSUE THREAD

**Issue by drekadottir621** [davidsansome/tsurukame#608] opened 2023-02-05 15:36 UTC
I noticed I wasn't getting a couple of reviews on Tsurukame and only on wanikani.com and I saw that they were all words that had recently changed to a level higher than mine (for example 作用 and 外れる, which are now lv 23 and lv 19 respectively, whereas I'm lv 8). Tsurukame still reports these as unlocked and mentions a next review timer but it doesn't actually let me review them.

I'm not sure if this is an issue specific to Tsurukame, because another third party app, Jakeipuu, has the same issue. However given that Tsurukame still recognises the word as unlocked, I'm guessing it's on the app level.

**Comment by drekadottir621** [comment] 2023-02-05 15:43
[local-cache.txt](https://github.com/davidsansome/tsurukame/files/10611431/local-cache.txt)

I wasn't sure how to upload this as a .db on mobile (ios just wouldnt let me) so I just changed the extension to .txt, I hope that's not a problem

**Comment by drekadottir621** [comment] 2023-02-05 17:41
Update: Tsurukame doesn't show them in the review forecast either, but Jakeipuu does, so I might have been wrong about it being an issue there too. Seems like it's definitely at the app level

**Comment by drekadottir621** [comment] 2023-02-05 17:42
Update: Tsurukame doesn't show them in the review forecast either, but Jakeipuu does, so I might have been wrong about it being an issue there too. Seems like it's definitely at the app level

**Comment by UInt2048** [comment] 2023-02-05 19:00
I know it’s tech support 101, but can you tell me if logging out of the app and back in fixes the issue?

**Comment by drekadottir621** [comment] 2023-02-05 19:03
> I know it’s tech support 101, but can you tell me if logging out of the app and back in fixes the issue?
I'll check next time one of those reviews come up. I might also try with a new API token if that doesn't fix it (which I presume it won't)

**Comment by drekadottir621** [comment] 2023-02-06 12:16
> I know it’s tech support 101, but can you tell me if logging out of the app and back in fixes the issue?

I tried logging out and back in as well as making a new API token but the review still isn't showing up.

**Comment by UInt2048** [comment] 2023-02-11 12:35
@drekadottir621 I forgot #569 hasn't been merged yet -- this is a duplicate of #591.

**Closed** 2023-02-12 06:38 UTC
