### ISSUE TITLE
App crash when swiping back on iOS 13

### ISSUE THREAD

**Issue by Chris-Peterson444** [davidsansome/tsurukame#175] opened 2019-10-07 19:57 UTC
When reviewing any radicals, kanji, or vocab, the app will crash if I swipe left. 

However, pressing back works fine, as well as swiping through levels in Show All. 

Here's an example:
![AppCrashOnSwipe](https://user-images.githubusercontent.com/27789757/66344020-ad1b5700-e901-11e9-8bd8-4cecbc1ffdcb.gif)

**Comment by davidsansome** [comment] 2019-10-12 01:41
I couldn't reproduce this but I can definitely see it's a top-reported crash on iOS 13.  I've put in a change that might fix it, but I'm not sure.

**Comment by bmironer** [comment] 2019-10-28 21:15
Crashes also when swiping left to right or right to left on that screen during reviews

**Comment by bmironer** [comment] 2019-10-28 21:17
It crashes when you let go mid-page. If you swipe slowly all the way so the current page is gone it works like a tap on back. 
Mixup between current/destination controller during the segue maybe?

**Comment by pearod** [comment] 2019-11-02 16:55
Started happening to me pretty consistently during reviews after updating to iOS 13.2.

**Comment by abdulajet** [comment] 2019-11-03 17:01
Here is another reproduction if this helps. running iOS 13.2
![tsurukame](https://user-images.githubusercontent.com/15106299/68088892-792d4600-fe5b-11e9-8714-9983fcc467df.gif)

**Comment by anduril11** [comment] 2019-11-05 14:39
Same issue here, happens every time on iOS 13.2 iPhone 11pro and iPad Pro 10.5.

**Comment by bengarland** [comment] 2019-11-10 01:11
I’m also seeing this crash 100% of the time when I try to back-swipe out of a level or two of component (radical or kanji) item info when in Lessons or Review. Top level back-swipe, e.g between Lesson items, does not crash. iPhone 8+, iOS and Tsurukame are all up to date.

**Comment by bulkan** [comment] 2019-11-12 01:16
This is fixed for me with the latest update

**Comment by davidsansome** [comment] 2019-11-12 01:27
That's awesome, thanks for letting me know!
If anyone sees this crash again after the update please re-open, but otherwise I'll assume this is fixed now.

**Closed by davidsansome** 2019-11-12 01:27 UTC
