### ISSUE TITLE
Incorrectly marking answers as wrong - 毎年 and 毎月

### ISSUE THREAD

**Issue by hak33m16** [davidsansome/tsurukame#768] opened 2024-10-27 20:51 UTC
https://community.wanikani.com/t/incorrect-audio-playing-for-some-words/67519

I’m having an issue with these two words where the audio that plays and the answer that’s accepted is different

Wanikani admins are claiming this is an issue with tsurukame incorrectly marking the answer as wrong, rather than wiggling. e.g. まいねん shouldn’t trigger an error even though it’s まいとし according to the admin

Though this doesn’t line up with the fact that the random audio track which comes back will sometimes play まいねん instead of まいとし

**Comment by davidsansome** [comment] 2024-11-17 01:07
Duplicate of #752

**Closed by davidsansome** 2024-11-17 01:07 UTC
