### ISSUE TITLE
Anki mode reviews do not work correctly when back to back is selected. 

### ISSUE THREAD

**Issue by Dazgra** [davidsansome/tsurukame#705] opened 2024-04-09 00:56 UTC
If you mark your answer as incorrect, the same card appears immediately. There is no way to mark your answer as incorrect and move on to another question. This issue has persisted for several months.

**Comment by UInt2048** [comment] 2024-04-09 12:44
Duplicate of #694 and #696

**Comment by Dazgra** [comment] 2024-06-10 00:40
Still not fixed 6 months later.

**Closed** 2024-06-11 12:25 UTC
