### ISSUE TITLE
Request: User Synonyms

### ISSUE THREAD

**Issue by tallerasaf** [davidsansome/tsurukame#582] opened 2022-08-25 12:50 UTC
Add/Edit User Synonyms in reviews and lessons.

**Comment by UInt2048** [comment] 2022-08-25 17:54
Adding user synonyms can already be done in reviews (turn on allow cheating).

Editing somehow appears not to have been requested before…

For completeness, deleting would be a duplicate of #169 and others.

**Comment by tallerasaf** [comment] 2022-08-25 20:48
> Adding user synonyms can already be done in reviews (turn on allow cheating).
> 
> 
> 
> Editing somehow appears not to have been requested before…
> 
> 
> 
> For completeness, deleting would be a duplicate of #169 and others.

I mean adding User Synonyms in Lessons

**Comment by UInt2048** [comment] 2022-08-25 21:28
That would be a duplicate of #301 then

**Comment by tallerasaf** [comment] 2022-09-12 00:15
> Adding user synonyms can already be done in reviews (turn on allow cheating).
> 
> 
> 
> Editing somehow appears not to have been requested before…
> 
> 
> 
> For completeness, deleting would be a duplicate of #169 and others.

@UInt2048 

Actually I turned on allow cheating and I am not able to edit the User Synonyms

**Comment by tallerasaf** [comment] 2023-07-03 18:30
> Adding user synonyms can already be done in reviews (turn on allow cheating).
> 
> 
> 
> Editing somehow appears not to have been requested before…
> 
> 
> 
> For completeness, deleting would be a duplicate of #169 and others.

@UInt2048 are you able to edit user synonyms on lessons or reviews? Even if I turned on "Allow cheating" it doesn't work.

**Comment by UInt2048** [comment] 2023-07-04 15:19
@tallerasaf When not using Anki mode, the “add synonym” button within the “+” menu works normally on meaning reviews.

**Comment by tallerasaf** [comment] 2023-07-05 02:15
> @tallerasaf When not using Anki mode, the “add synonym” button within the “+” menu works normally on meaning reviews.

@UInt2048 I did as you said and it did not work:
![image](https://github.com/davidsansome/tsurukame/assets/14837253/6b312433-987d-4380-920d-26e110e1864a)

**Comment by UInt2048** [comment] 2023-07-05 14:30
@tallerasaf Must be a meaning review. You can’t add a wrong reading like さげる as a “reading synonym” — WK doesn’t allow that for obvious reasons

**Comment by tallerasaf** [comment] 2024-01-02 13:37
![image](https://github.com/davidsansome/tsurukame/assets/14837253/b89e3f4f-0702-42d6-a676-5493695efaac)
![image](https://github.com/davidsansome/tsurukame/assets/14837253/6838f11d-40a5-40ab-8b62-4153d677d32d)

@Deadpikle You have time to add a new feature that will enable to add and edit "User Synonyms" in Lessons and Reviews like in the WaniKani website?

**Closed** 2024-04-28 23:11 UTC
