### ISSUE TITLE
頁 not accepting ページ as an answer

### ISSUE THREAD

**Issue by Llorely** [davidsansome/tsurukame#784] opened 2024-12-10 04:19 UTC
Hello, 

Lately 頁 is not accepting ページ as a suitable answer.
I remember it used to work before as I have learned and made progress on this kanji, but now I can’t seem to get the answer right.
I’m using an iOS device, if that’s useful.
Thank you!

**Comment by davidsansome** [comment] 2024-12-10 05:53
Duplicate of #777. This is fixed in the TestFlight build already!

**Closed by davidsansome** 2024-12-10 05:53 UTC
