### ISSUE TITLE
Feature Request: Verbal Recall

### ISSUE THREAD

**Issue by dav1dpgit** [davidsansome/tsurukame#410] opened 2020-09-20 15:28 UTC
**Minor Annoyance:**

Sometimes for both speed and verbal recall, I use the microphone on my iOS device for English meanings. I cannot do this for Japanese meaning because the English keyboard is being used.

**Possible Solution?**

When the English keyboard is showing the app is set to expect a Japanese reading response when the microphone is selected.  When the English meaning is being expected the microphone will be listening for English responses (this would be unchanged.)

**Comment by UInt2048** [comment] 2020-09-20 23:40
@dav1dpgit There's already an auto-switch keyboard setting for this.

Please close this issue if that solved your problem. Otherwise, please explain further.

**Comment by dav1dpgit** [comment] 2020-09-21 17:32
Thanks for the rapid response and apologies if this is not clear.  I was hoping you could automate converting verbal dictation to hiragana when the app requests Japanese pronunciation as you did for the QWERTY keyboard being converted to hiragana when typing the pronunciation.

Currently, when I want to use dictation to respond to the app’s request for Japanese pronunciation I am required to select the globe icon in order to switch to a different language dictation.  This also causes the hiragana to be auto-converted to kanji (auto conversion to kanji is a setting I want to use in other apps such as email.) In your app, with the QWERTY keyboard the hiragana automatically appears which is good. In addition, the typed hiragana is not converted to kanji, which is also good.  I was hoping you could 1) have the app recognize Japanese dictation when Japanese pronunciation is required, and 2) also ensure that dictated Japanese does not get converted to kanji.

**Comment by UInt2048** [comment] 2020-09-22 18:46
@dav1dpgit I would recommend closing as a duplicate of #360.

There is no way for you to make an English keyboard treat Japanese dictation as Japanese, but we could accept kanji as described there.￼

**Comment by dav1dpgit** [comment] 2020-09-24 02:07
Thanks for this; I will take a look at #360 in depth as it looked like it was more interested in having a hi recognized.

On my request, a question:  How does Tsurukame reflect a western QWERTY keyboard, but as I type responses to Japanese pronunciation, kana is reflected?  Appears dichotomous to have kana conversion for a qwerty keyboard but expecting English pronunciation.

**Comment by UInt2048** [comment] 2020-09-24 11:06
@dav1dpgit There's a kana input converter at `/ios/TKMKanaInput.m` which will convert your input to kana as you type it. If you look at it, you'll see a list of all possible conversions. You can't do that with audio - what you get would be nothing like what you meant!

**Comment by dav1dpgit** [comment] 2020-09-24 17:39
Yes, then audio version comes out as English words.

Thanks for the insight—I will close the issue.

**Closed** 2020-09-24 17:40 UTC

**Comment by dav1dpgit** [comment] 2020-10-09 23:25
One follow-up question on this: was issue #360 (#360 )ever implemented?  I don’t see it’s functionality.

**Comment by UInt2048** [comment] 2020-10-10 16:12
@dav1dpgit No, that's why it's still open.

**Comment by dav1dpgit** [comment] 2020-10-10 23:11
Thanks.  I love your app.  Everything works so well and smoothly.

**Comment by UInt2048** [comment] 2020-10-13 00:20
@dav1dpgit I'm not actually the owner, but it is pretty great! 👍
