### ISSUE TITLE
iOS Search bar not working

### ISSUE THREAD

**Issue by kureiton** [davidsansome/tsurukame#297] opened 2020-02-09 00:59 UTC
Since updating to the latest version, search  results are not appearing for Kanji or vocabulary anymore, nearly all the results are radicals.
![57AC8E14-6789-431A-B346-CF3E41B5976D](https://user-images.githubusercontent.com/60831231/74094326-c7b94300-4b22-11ea-90a8-ff9549a13e52.png)

**Comment by turtlemaster19** [comment] 2020-02-09 01:01
I think this is a dupe of #272

**Comment by kureiton** [comment] 2020-02-09 03:56
Ah, sorry about that.

According to the App Store. I have the latest version. Is there a way to download the latest master without a jail broken iPhone?

Sorry, I’m not very good with technology.

**Comment by turtlemaster19** [comment] 2020-02-09 12:48
@kureiton You don't need a jailbreak, or even a Mac. Simply click on the TestFlight link in the README. It's also possible to build from source if you have a Mac, but that's more complicated, and only lasts seven days.

**Comment by kureiton** [comment] 2020-02-09 14:01
Fantastic! Got it up and running, thank you so much for you help!

Tsurukame is great!

**Comment by turtlemaster19** [comment] 2020-02-09 14:01
@kureiton Please close this issue.

**Comment by kureiton** [comment] 2020-02-09 14:04
Sorry!

**Closed** 2020-02-09 14:03 UTC
