### ISSUE TITLE
Dynamic text not supported for JP text

### ISSUE THREAD

**Issue by abdulajet** [davidsansome/tsurukame#509] opened 2021-08-04 19:57 UTC
Not sure if this is intentional or  not ![image](https://user-images.githubusercontent.com/15106299/128246414-e5f19aa6-a2a7-4370-9bda-cfaca0defb0d.jpeg)

**Comment by UInt2048** [comment] 2021-11-09 22:57
Looks like a dupe of #334

**Closed** 2021-11-19 17:32 UTC
