### ISSUE TITLE
App doesn’t recognise correct input for 頁

### ISSUE THREAD

**Issue by jjimboy** [davidsansome/tsurukame#780] opened 2024-11-25 19:58 UTC
Hi there, love the app and wouldn’t bother reporting an issue if I didn’t intend to keep using it. Thanks for all your hard work. 

The app recognises neither ページ nor ぺーじ as acceptable inputs for the character 頁. This issue does not occur on the WaniKani website so I assume there’s something going on in the app. 

Thanks again!

**Comment by davidsansome** [comment] 2024-11-26 16:53
Duplicate of #777

**Closed by davidsansome** 2024-11-26 16:53 UTC
