### ISSUE TITLE
Crash on swipe back 

### ISSUE THREAD

**Issue by remyGrandry** [davidsansome/tsurukame#192] opened 2019-11-05 07:27 UTC
Hello,

First of all thanks for this application it’s a really awesome one.
I found a bug which is, when you are in a review or a lesson, if you click a kanji or a radical in the description (where there is the meaning, readings, similar kanji etc), if you swipe back instead of pushing the arrow to get back to your review, the app will crash.

Thanks a lot

**Comment by turtlemaster19** [comment] 2019-11-05 13:09
Same as #175 
Can't reproduce on iPadOS 13 - will try on phone in a little bit

**Comment by davidsansome** [comment] 2019-11-06 07:57
Yep this is a duplicate of #175.

**Closed by davidsansome** 2019-11-06 07:57 UTC
