### ISSUE TITLE
Possible to open "phantom" item detail page

### ISSUE THREAD

**Issue by lyallcooper** [davidsansome/tsurukame#143] opened 2019-07-16 20:54 UTC
During reviews and the lesson quiz, it's possible to open a "phantom" item detail page (see second screenshot below) by tapping in the area where the previously completed item normally shows during reviews as shown in the first screenshot. The only way to get back from this view is to use the swipe from the left edge of the screen.

It seems to always be possible to enter this view during the lesson quiz but only possible during reviews if there is no previously completed item.

How to trigger:
![IMG_4239](https://user-images.githubusercontent.com/894902/61328838-c1532a80-a7d0-11e9-89f5-ecd0e1c99e8d.PNG)
The "phantom" item detail page:
![IMG_4240](https://user-images.githubusercontent.com/894902/61328844-c3b58480-a7d0-11e9-9863-5200f83f856c.PNG)

**Comment by davidsansome** [comment] 2019-07-18 05:56
I think this is a duplicate of #113

**Closed by davidsansome** 2019-07-18 05:56 UTC

**Comment by lyallcooper** [comment] 2019-07-18 17:10
Ah yep looks like it. Tried to search but didn't find it myself. Sorry for the duplicate!
