### ISSUE TITLE
Kanji display area no longer allows a single tap to reveal default font

### ISSUE THREAD

**Issue by bengarland** [davidsansome/tsurukame#271] opened 2020-01-18 10:03 UTC
Since some recent app update, if you have multiple fonts turned on, tapping in the kanji display area no longer temporarily shows the kanji in the standard font (this is handy if the displayed font is really messy and you can't read it) -- now it seems you have to tap and do a short drag either up or down to show it. It's a very subtle difference, but being able to tap (without having to drag a few pixels) to show the standard font was a lot easier.

**Comment by bmironer** [comment] 2020-01-18 10:52
Additionally dragging Left with scroll through all the fonts, which is nice. Dragging right switches to standard font.
I’m still not sold on the current implementation although I got used to it fairly fast. I feel it’s surprising and lacks discoverability.
Maybe tapping for standard and dragging to scroll through fonts?
Adding page dots or a handle to show it’s draggable? 
It’s still very convenient to have the whole top half of the screen the target so you can tap anywhere.

**Comment by bmironer** [comment] 2020-01-18 10:56
Or is it simply that dragging left and right are different? 
Maybe left/right should scroll through fonts in opposite order and have dragging down go to standard font. 
Might be difficult to properly distinguish short drags though.

**Comment by turtlemaster19** [comment] 2020-01-18 13:04
This is intended behavior introduced by #232. See https://community.wanikani.com/t/ios-tsurukame-native-app-with-offline-lessons-and-reviews/30635/502

**Comment by davidsansome** [comment] 2020-01-18 23:49
I dunno... the swiping was intended but I didn't realise that broke the old behaviour.  I guess the tap gesture recogniser needs to wait for the drag recogniser to fail, so has a short delay before it works.
Let's see if we can fix this, or at least make the delay shorter.

**Comment by bengarland** [comment] 2020-01-18 23:56
I realized I can do a short drag-left to show the default font which isn’t nearly as hard to execute as drag-up (or down) for me. But yeah the old instant tap to reveal would be better.

(I like all of the improvements recently!)

**Comment by turtlemaster19** [comment] 2020-01-20 16:59
@mzsanford, since you're not watching the repo, I thought you may want to see this issue.

**Comment by mzsanford** [comment] 2020-01-20 21:28
The swipe was expected in #232 but the tap should not have been broken. From that code it looks like it was already a `UILongPressGestureRecognizer` and since I wasn't using the feature I didn't realize how it was being used. It sounds like we want:

 1. Short-Tap should switch to "normal" font
 2. Long tap should reveal "normal" font but return to the special font on release
 2. Swipe should change fonts - currently it goes to a random font. Would it be better ordered?

Is that correct?

**Comment by bmironer** [comment] 2020-01-20 22:19
1. / 2. Not sure. I used to simply put my finger up and down to compare the printed vs written for the less legible glyphs, especially with Armed Banana. Now I slightly drag right and release.  For 1. at least have a second shirt tap go back to the written version but that seems even less practical so I’d rather have 2. on a short tap. 

3. It should probably use the order of the fonts in the settings. Can we make the list reorderable ?

**Comment by mzsanford** [comment] 2020-01-20 23:56
@bmironer  I started testing this and I added a single tap that switches between "normal" and "random". It feels like this sort of replaces the long press as you could tap once to go to normal, and tap again to return. Having three gesture recognizers where two are long interactions (hold vs swipe) means having to delay changes to see which once it is and it feels overly complicated form both the code and UX. Your thoughts?

I'll look at cycling through fonts in a set order. As for the order, changing settings to allow reordering feels like a bit of feature creep. I would like to get this working for the next App Store release and then revisit Settings reordering once we have it functional and people can try it out.

**Comment by bmironer** [comment] 2020-01-21 08:02
We need to test it I believe.
I agree that having both short and long presses would be complicated, error prone, and maybe not at all discoverable. Took a bit to figure out how the current version works since there isn't a target, handle or hint. 
Also I don't think it should be a global switch between random and normal if that's what you mean.(that would be in settings or in the quick menu)
It's just a quick glance at the legible printed version (as it was in the previous version) for when we're not sure. And then the next review would use another font (randomly), as it is now.

Reordering the fonts in the settings is definitely feature creep and not urgent/needed at all.
However I think I might have though of that because Armed Banana is first in the list and the less legible to me. So probably not the one I'll want to see first ever.
I hate it. But I still want to see it so I can train. Especially on higher SRS levels. 
But I still hate it so I disable it on lower SRS levels when I'm still memorizing and or starting a new lesson.

**Comment by bmironer** [comment] 2020-01-21 08:10
Or a completely different idea : 
Forget swiping / scrolling fonts.

Add a small row of the current kanji in font variants just above the 'Kanji meaning/reading prompt' Tap the small kanjis to switch to that font. 
Make the panel optional in settings.

Then restore the previous functionality for the main panel : 
Select one at random for each review (in settings), as it used to.
Tapping in the big kanji space to temporarily display the printed version, as it used to.

**Comment by bengarland** [comment] 2020-01-21 08:21
I started this issue, and frankly I consider it solved now that I know all I have to do is tap and very slightly swipe right to reveal the legible standard font. Swipe left is okay to show other fonts. Any long-tap-and-wait functionality can be removed as far as I'm concerned, if it helps clean up the code or reduce tap/drag conflicts.

**Comment by mzsanford** [comment] 2020-01-21 17:04
@bmironer I'm awaiting app store review for a new TestFlight (1.18). This includes all of the changes from the past week plus Apple Watch and my proposed font changes. Give it a try when it comes out. The tap handler works like you suggest, if you tap it toggles between normal and custom fonts. the next item picks a random one again to start. This also uses swipe to cycle through fonts in a predictable order.

I like the idea of attempting to show multiple fonts at the same time via a selector. It's a bit outside if the current scope but I'll keep it in mind.

@bengarland I'm happy that it's solved. I think the tap thing will be simpler for the user and the code. If you're not on the TestFlight you can join it and try out once v1.18 is approved.

**Comment by turtlemaster19** [comment] 2020-01-21 17:05
@bmironer @bengarland @mzsanford David Sansome just shared the link for the official TestFlight in this post: https://github.com/davidsansome/tsurukame/pull/273#issuecomment-576779237

**Comment by bengarland** [comment] 2020-01-22 00:04
Hmm I’m on 1.18 now and it looks like nothing really changed regarding this issue. A short tap still does nothing, I still have to tap and slightly drag right to show the standard font.

**Comment by turtlemaster19** [comment] 2020-01-22 00:32
@bengarland Oops. I thought that the changes had already been merged: they haven't.

@mzsanford Could you submit a PR?

**Comment by mzsanford** [comment] 2020-01-22 01:38
@bengarland it is in the unofficial TestFlight only (TF Name: Tsurukame MZSanford). Is that the one you're using? I know that it's confusing with two. 

@turtlemaster19 I want to make sure it working before submitting a PR since the app store road is long and slow. I'm at 2 PRs already around this feature so I'm hoping to get direct feedback via the unofficial TestFlight and iterate. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bengarland** [comment] 2020-01-22 03:20
@mzsanford Oh sorry, yeah I'm only on the official test build.

**Comment by bmironer** [comment] 2020-01-22 07:58
Tried it this morning. 

- Double tapping to go back and forth between standard and custom fonts. 

It kinda felt more cumbersome than tap-and-release at first. 
But it's definitely easier to discover and understand than tap-and-drag-right.
I could get used to it I guess. 
Definitely an improvement.

- Swiping left changes the font (as it already does).
but swiping right doesn't do anything 
I feel swiping left and swiping right should have opposite effects.

**Closed** 2020-01-25 07:58 UTC
