### ISSUE TITLE
App crashed on sign-in!

### ISSUE THREAD

**Issue by lucymation** [davidsansome/tsurukame#263] opened 2020-01-16 17:08 UTC
Hiya, I just tried to log in and the app crashed immediately. It won't re-open either.
I'm using iOS 13.1.2 on an iPhone 6s for reference.

Thank you for the app, so excited to use it!! :)

**Comment by turtlemaster19** [comment] 2020-01-16 17:09
Try your email instead of the username

**Comment by lucymation** [comment] 2020-01-16 17:11
I can't actually open the app to do so, it crashed immediately!

**Comment by lucymation** [comment] 2020-01-16 17:34
I just deleted the app, tried to sign in using my username and the same thing happened sadly!

**Comment by turtlemaster19** [comment] 2020-01-16 17:38
I can't experience this on any of the three builds. Can you share your WK level and what type of subscription you have?

**Comment by lucymation** [comment] 2020-01-16 17:40
I've just started WK, so I'm level 1! Is that anything to do with it?
I'm sorry I don't know how to get an APIv2 key!

**Comment by turtlemaster19** [comment] 2020-01-16 17:57
Go make one here: https://www.wanikani.com/settings/personal_access_tokens

**Comment by lucymation** [comment] 2020-01-16 17:59
Thanks! I appear to already have one, what do you suggest?

**Comment by turtlemaster19** [comment] 2020-01-16 18:02
I'll go test on my testing account and see if I can reproduce. I have an idea, but I need to make sure that the problem is on our side.

**Comment by turtlemaster19** [comment] 2020-01-16 18:13
@lucymation Were you able to log in into the TestFlight build?

**Comment by lucymation** [comment] 2020-01-16 18:16
I'm just attempting now, thank you!

**Comment by lucymation** [comment] 2020-01-16 18:19
I'm in on testflight!! The dashboard animated in about 3 times, but it appears to work!

**Comment by turtlemaster19** [comment] 2020-01-16 18:22
@lucymation Great! The App Store release is a bit behind the latest master, so I am glad this worked for you! Please close this issue, since we're trying to get a new release out to the App Store.

**Comment by lucymation** [comment] 2020-01-16 18:23
No problem, thanks so much for having a look! I look forward to using this for wanikani :)

**Closed** 2020-01-16 18:23 UTC

**Comment by mzsanford** [comment] 2020-01-16 18:30
For the record, I think this by a call to `getAssignmentsAtLevel`, via `getAssignmentsAtUsersCurrentLevel` which deep inside attempts `level -1` … which for level `0` ends up as `18446744073709551615`. I'll push a fix for that ahead of my Testflight Apple Watch branch

**Comment by turtlemaster19** [comment] 2020-01-16 18:32
There's no such thing as level 0. By the way, why did it work in the TestFlight then?

**Comment by davidsansome** [comment] 2020-01-17 03:36
I've pushed a new build to the App Store to fix this crash, hopefully it'll be live tomorrow!

**Comment by davidsansome** [comment] 2020-01-17 09:56
The new version is now live in the app store!
