### ISSUE TITLE
Apostrophe problem with newest update

### ISSUE THREAD

**Issue by tukaani1** [davidsansome/tsurukame#165] opened 2019-08-19 15:38 UTC
Hello! First – thanks for the great app and update. One minor problem: tried to input ハートがた several times, it always came up false. Even when I tried katakana (see screenshots). I guess it is due to the apostrophe? No problems with other words. This hasn’t happened with the same word before today. 

![43053174-FCC2-4940-8A3A-4B034A4346E2](https://user-images.githubusercontent.com/54281089/63278605-3faf5a80-c2b0-11e9-9ab9-4323bb65f569.jpeg)
![6E2198D7-9B86-422D-8DD5-85254894F3EB](https://user-images.githubusercontent.com/54281089/63278606-3faf5a80-c2b0-11e9-879c-275c6bdfaef2.jpeg)

**Comment by davidsansome** [comment] 2019-08-19 22:18
Duplicate of #160.  I actually fixed it yesterday - there should be an update available in the App Store now for you to install.

**Closed by davidsansome** 2019-08-19 22:18 UTC
