### ISSUE TITLE
App crashes when clicking on reviews

### ISSUE THREAD

**Issue by Afsy1** [davidsansome/tsurukame#662] opened 2023-09-15 14:11 UTC
App crashes when trying to open reviewed on iPhone. Almost every time now.

**Comment by davidsansome** [comment] 2023-09-15 14:27
Duplicate of #658

**Closed by davidsansome** 2023-09-15 14:27 UTC

**Comment by UInt2048** [comment] 2023-09-15 15:28
@Afsy1 You can get the fix by installing TestFlight build 981 or newer

**Comment by Afsy1** [comment] 2023-09-16 01:46
For iPhone? How will this all help the issue?

**Comment by UInt2048** [comment] 2023-09-16 10:25
@Afsy1 There’s a [TestFlight beta](https://testflight.apple.com/join/Fijye2AA) of Tsurukame that has the fix available to test
