### ISSUE TITLE
App freezes

### ISSUE THREAD

**Issue by RitwickSV** [davidsansome/tsurukame#639] opened 2023-05-28 00:54 UTC
App frozen from about 3days. Encountered the issue at これ. Used wanikani on my laptop to get past that hurdle. But now the lessons dont open at all. The app is completely frozen where the touch is irresponsive.

**Comment by davidsansome** [comment] 2023-05-28 03:28
Duplicate of #636

**Closed by davidsansome** 2023-05-28 03:28 UTC
