### ISSUE TITLE
Items incorrectly shown as locked

### ISSUE THREAD

**Issue by Rion-Kaneshiro** [davidsansome/tsurukame#87] opened 2019-01-04 17:12 UTC
I noticed that I have some items marked as locked although they are already on guru level.

That also lead to a review that was not shown while using the app, but did show up on the wanikani website.

**Comment by bmironer** [comment] 2019-02-01 13:48
Possibly the same bug : I've got lessons (not reviews) available on the web site but they do not appear in the app, even after killing and refreshing...

**Comment by turtlemaster19** [comment] 2019-10-24 12:00
This still occurs now. You can reproduce by reviewing offline, then checking your items remaining in-app before reconnecting online.

**Comment by davidsansome** [comment] 2019-10-29 00:58
I think I fixed this in 4acbb3c4f46af89b324769c3f3e0ad165f98d80d but maybe there are still some cases I missed.

**Comment by turtlemaster19** [comment] 2019-11-15 02:05
Not yet fully resolved.
![IMG_7191](https://user-images.githubusercontent.com/46784000/68911263-f7220480-0719-11ea-88ce-3e1d17b0c821.JPG)
Although some items have been removed for brevity, there is still a (hidden) distinction between uploaded and non-uploaded items. This is better, but could the word "pending" be used if we're going to keep it distinct (e.g. Pending Guru I vs. Guru I)

**Comment by turtlemaster19** [comment] 2019-11-25 13:09
Let me ask, is it intended behavior to not allow Reviews for an item that has been Reviewed offline until it syncs? If it is, we can close this. If not, then we probably should leave it open.

**Comment by turtlemaster19** [comment] 2020-01-07 00:20
According to https://community.wanikani.com/t/api-v2-beta-documentation/18987/753, it would be possible to do multiple reviews for an item offline. This issue should remain open until it is possible to start the next timer offline, or it is clear that it is intended behavior (it's not a bug, it's a feature)

**Closed** 2020-02-17 03:37 UTC
