### ISSUE TITLE
Version 1.11 not syncing 

### ISSUE THREAD

**Issue by pbuzek** [davidsansome/tsurukame#159] opened 2019-08-16 21:32 UTC
I updated to 1.11 and completed reviews are not getting synced. App shows “46 review progress “ and I’m online. I tried closing the app, disconnecting from WiFi, still nothing. 
iOS 12.3.1 on iPhone 6s

**Comment by nyfrit** [comment] 2019-08-17 00:55
Same issue on iPhone XS 139 reviews pending synchronization. Was working properly until I updated earlier today.

**Comment by indirect** [comment] 2019-08-17 04:54
@pbuzek @nyfrit log out and then back in to resolve this issue, this is a duplicate of #122.

**Comment by norbertpotocki** [comment] 2019-08-18 17:32
a big warning here: signing out will cost you your progress.. just lost 600 reviews this way..

**Comment by indirect** [comment] 2019-08-19 00:12
Reviews that are stuck cannot ever be uploaded by the current version, sorry. If you're a skilled iOS developer you could manually build and install an older commit to upload those reviews, then update to the latest, then log out and back in. If you aren't a skilled iOS developer, you can wait to sync those reviews for days (or weeks or months) until we develop a fix—or you can log out and back in, losing your review queue, and get things working right away.

**Closed** 2019-08-19 03:26 UTC

**Comment by davidsansome** [comment] 2019-08-19 03:30
Apologies for this.  The API token that Tsurukame used before the upgrade didn't have write-access to your account, so isn't able to upload reviews.

I've got a new version that's waiting for App Store review now - when you install it it'll ask for your password again, create a new API token, and upload your saved reviews.

*Don't* log out and back in again if you want to keep your reviews.
