### ISSUE TITLE
Bug/Feature Request? Customise auto reveal setting

### ISSUE THREAD

**Issue by samcrossbabylonhealth** [davidsansome/tsurukame#321] opened 2020-03-21 13:05 UTC
So, I have the "Reveal answer automatically" setting set to "Off", yet if I get an answer wrong twice the answer immediately _does_ reveal automatically.  

Presumably this was a design choice yet personally if I had this setting "On" I would like to customise the amount of wrong answers before an auto reveal (e.g. have the aforementioned setting "On" and a new setting "Number of incorrect answers before reveal" set to "4").  

Feels to me like the setting needs expansion basically, since it doesn't work how I'd expect it to at the moment.

**Comment by turtlemaster19** [comment] 2020-03-21 14:32
I agree wholeheartedly with this. Perhaps the two answers was chosen, since if you get it wrong a third time, it goes down **another** SRS stage.

**Comment by turtlemaster19** [comment] 2020-05-16 01:11
@samcrossbabylonhealth It seems to be a bug caused by looking to see if the setting is on **and** it is the first time instead of **or**. This should be fixed in the combined PR.

**Comment by samcrossbabylonhealth** [comment] 2020-07-22 12:20
I saw David's comment on the monster PR...can we pull this small fix into its own PR easily?

**Comment by UInt2048** [comment] 2020-07-23 15:07
@samcrossbabylonhealth Done. Hopefully it will be merged!

**Closed** 2020-08-02 02:29 UTC
