### ISSUE TITLE
Vocabulary sounds not appearing

### ISSUE THREAD

**Issue by R188** [davidsansome/tsurukame#513] opened 2021-09-02 05:22 UTC
The option to play the audio for some words aren't there at all, one would be 言葉つき.

Edit: Went on the app some more and none of the vocabs have audio buttons at all or play audio.

**Comment by UInt2048** [comment] 2021-09-02 10:11
Please close this issue - duplicate of #512

**Closed** 2021-09-02 10:17 UTC
