### ISSUE TITLE
Feature Request: Support for Extra Study

### ISSUE THREAD

**Issue by catorar** [davidsansome/tsurukame#627] opened 2023-05-01 12:12 UTC
WaniKani introduced the Extra Study feature in March 2022. It would be handy to have access to this feature within the Tsurukame app if possible.

https://knowledge.wanikani.com/getting-started/extra-study/

**Comment by UInt2048** [comment] 2023-05-01 14:31
Duplicate of #446 and #556

**Closed** 2023-12-29 01:34 UTC
