### ISSUE TITLE
Audio Controls disappeared

### ISSUE THREAD

**Issue by ihavenotea** [davidsansome/tsurukame#515] opened 2021-09-02 19:10 UTC
The audio controls in app (and automatic playback) have disappeared for me. 

I first noticed it while using Tsurukame while playing Apple Music on an Apple TV. 

There does not appear to have been a new Tsurukame release recently to account for this. 

(Perhaps apple changed a library. Perhaps I found a weird edge case in the audio libraries when streaming multiple content source)

I have attempted to restart the app and my phone but the problem persists.

**Comment by bmarkus86** [comment] 2021-09-02 19:47
The same happened to me. I reinstalled the app and restarted my phone, but the audio controls are still missing. No button, no auto play.

**Comment by UInt2048** [comment] 2021-09-02 20:17
This is a duplicate of the just-fixed #512. It's being submitted to the App Store as we write this.

Please close this issue (and download the TestFlight beta if you want the fix now.)

**Closed** 2021-09-02 23:21 UTC
