### ISSUE TITLE
Level 10 bug with geoduck

### ISSUE THREAD

**Issue by rukmini-singh** [davidsansome/tsurukame#789] opened 2024-12-29 06:49 UTC
The kanji reading for geoduck keeps not being accepted in the Tsurukame app despite being right (ページ)

**Comment by bouchbi** [comment] 2024-12-30 06:41
Had the exact same issue this morning.
Solved it by reviewing it on the wanikani website.
I’ve sent an email to the developer as well to notice this behaviour

**Comment by davidsansome** [comment] 2024-12-30 10:57
Duplicate of #777

**Closed by davidsansome** 2024-12-30 10:57 UTC
