### ISSUE TITLE
Correct answer not accepted 

### ISSUE THREAD

**Issue by Lifimari** [davidsansome/tsurukame#779] opened 2024-11-25 16:34 UTC
For whatever reason, the correct answer is never accepted for the kanji “page (ペ-じ)” whether I write it in hiragana or katakana. The only thing I can do is to type in an incorrect answer and move onto the next word. What could be causing this? 

I have tried typing using the keyboard on my phone and I have even tried copying the correct answer/spelling directly from Tsurukame, but nothing seems to help. When the word first appeared, there were no issues, but now the correct response results in the word “shaking” similarly to how it would if I was trying to input a vocabulary reading instead of a kanji reading or the other way around. 

It is getting frustrating doing reviews and having to make the same error over and over during reviews until I only have the kanji “page “ left and I can end the review session.

Thank you for your help.

**Comment by davidsansome** [comment] 2024-11-25 16:35
Duplicate of #777

**Closed by davidsansome** 2024-11-25 16:36 UTC
