### ISSUE TITLE
App freezes when doing lesson for する, a new kana-only

### ISSUE THREAD

**Issue by milowyner** [davidsansome/tsurukame#636] opened 2023-05-24 19:16 UTC
The app seems to be handling the new kana-only vocabulary fine except for する. When I tap it or swipe in its direction in the lessons the app freezes and no touch inputs do anything until I force close and relaunch. I’m on iOS 16.5 using an iPhone 12 Mini in case that helps.

**Comment by matthewgrimes** [comment] 2023-05-24 20:07
Same for me. Also on an iPhone, a 12 pro running 16.4.1. 

I can also add that the other lessons went through but now する is the first lesson and clicking on the lesson tab from the home screen freezes the app.

**Comment by Twiglet1022** [comment] 2023-05-24 20:35
Same here but with これ. As a temporary workaround I was able to get past it by installing the TestFlight beta (which also freezes for that word) and disabling kana-only vocab lessons.

iPhone 14 Pro iOS 16.4.1 (a)

**Comment by MattMisrak** [comment] 2023-05-24 23:52
Same here first with これ and then with する after closing the app a few times and a few full refresh. 

iPhone 12 iOS 16.4.1(a)

**Comment by marciska** [comment] 2023-05-25 07:57
Might be because する verbs are specially handled when highlighting example sentences.
I suppose (!) that there might be something wrong with these checks now.
Searching for "suruverb" shows up [quite a few locations](https://github.com/search?q=repo%3Adavidsansome%2Ftsurukame+suruverb&type=code).

**Comment by Klhhff** [comment] 2023-05-25 08:36
Same problem here. これ and する

**Comment by marciska** [comment] 2023-05-25 08:45
I pushed a hotfix that solves the issue (for now). Let's hope it gets quickly integrated into the base branch!

It is only a temporary fix: making all suruVerb of class ichidanVerb. This prevents the app from crashing, but example sentences for other sure-verbs are coloured wrong. Exchanging a critical crashing-bug with “only” a visual appearance bug, so to speak. At least until a real fix is proposed.

**Comment by davidsansome** [comment] 2023-05-25 09:55
I've updated the TestFlight build with a fix for する. I wasn't able to reproduce the problem with これ though.

Would somebody be able to install 1.28 (972) from TestFlight and verify it works for both now?

**Comment by milowyner** [comment] 2023-05-25 16:00
Yep, する is now working on the latest TestFlight, and これ was previously working for me as well. Thanks for the quick fix!

**Comment by davidsansome** [comment] 2023-05-25 16:48
Thanks for confirming! I'll push an update to the App Store now.

**Comment by davidsansome** [comment] 2023-05-25 22:38
I'll leave this bug open until the fix rolls out so people can find it.

The new release is waiting for App Store review now.

**Comment by davidsansome** [comment] 2023-05-27 09:26
The release was rejected by Apple with an absurd question about the API token login option, despite that feature being present for several releases now 🙄. I've responded to the Apple reviewer and hopefully they'll re-review it soon.

**Comment by Motifier** [comment] 2023-05-28 22:14
Thought I'd ask in case it hadn't been addressed, but I've noticed that the app also freezes when trying to view the する from the level select page. I'm guessing the fix will likely also fix the app hanging there as well, but as I don't have the beta version installed currently, need someone else to confirm. It hasn't been mentioned above though.

**Comment by davidsansome** [comment] 2023-05-29 21:42
The release was finally approved! 1.28 is now on the App Store and I expect most devices should update automatically over the next few days.

**Closed by davidsansome** 2023-05-29 21:42 UTC
