### ISSUE TITLE
App crash on reviews (probably from fetching sound files)

### ISSUE THREAD

**Issue by cjljohnson** [davidsansome/tsurukame#352] opened 2020-04-30 17:33 UTC
Since the last update, Tsurukame often crashes when i am doing reviews.  I am guessing this has something to do with it requesting the sound files to play when answering a vocab word correctly, but i can't be sure as i can't find a crash report feature.

Not sure how to reproduce it, it seems to happen randomly.

**Comment by turtlemaster19** [comment] 2020-04-30 19:34
@cjljohnson Please provide more information:

What is the version number of the app? If it's lower than 1.20, update.

Can you send any debug logs of the crash (such as the local database found at the bottom of the Settings screen)?

Do you have a Mac with Xcode?

**Comment by cjljohnson** [comment] 2020-04-30 22:04
Version is 1.20. 

Here is the local-cache.db from the app.
[local-cache.zip](https://github.com/davidsansome/tsurukame/files/4561622/local-cache.zip)

I don't have a mac.

It has been happening for a few weeks, it's only recently that i noticed the pattern of it happening when answering a reading of a vocab which is what makes me think it is related to fetching the audio file after answering correctly.

I have not noticed a pattern of it happening with specific words, i can open the app again and do the reviews again without it crashing most of the time.

**Comment by turtlemaster19** [comment] 2020-04-30 22:38
@cjljohnson Try turning off "Play audio automatically" to see if that's what the problem is...

What OS version and device model do you have?
Mine is 13.3.1, iPhone 11, not experiencing.
I assume your OS version is at least 13.4?

**Comment by turtlemaster19** [comment] 2020-04-30 22:45
@cjljohnson You are receiving lots of HTTP 422 errors in the error log in the database (record invalid) suggesting something more like what #295 solved.

**Comment by turtlemaster19** [comment] 2020-04-30 22:55
@cjljohnson You are receiving lots of HTTP 422 errors in the error log in the database (record invalid) suggesting this being a duplicate of #277.

Could you check your date/time settings?

P.S. Congrats on making it to Level 20! Please expire your APIv2 token beginning with `226` since it is now publicly accessible...

**Comment by cjljohnson** [comment] 2020-04-30 23:10
Is there a setting for date and time other than for the phone as a whole?  The phone's time setting is correct to BST.

**Comment by turtlemaster19** [comment] 2020-05-01 00:49
@cjljohnson No, it's just too much error between the server and your phone.

**Closed** 2020-06-18 10:11 UTC
