### ISSUE TITLE
Pending review progress does not upload

### ISSUE THREAD

**Issue by joshgentry** [davidsansome/tsurukame#164] opened 2019-08-19 03:42 UTC
I'm using version 1.11 and as of this morning, my reviews refuse to be uploaded.

At the bottom of the main screen, it states:

> 170 review progress
> These will be uploaded when you're back online

I've attempted disconnecting from WiFi, pulling down and holding to refresh, doing the same when reconnected to WiFi, as well as restarting the app.

**Comment by davidsansome** [comment] 2019-08-19 03:44
Dupe of #159.  TLDR is there's a fix in review with Apple now, when you update all the saved reviews should start uploading.

**Closed by davidsansome** 2019-08-19 03:44 UTC
